// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-modules.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var MODULES = [
  { slug: "arrays", title: "Arrays", principle: "The Contiguous Block", path: "/algoviz/arrays" },
  { slug: "strings", title: "Strings", principle: "The Immutable Chain", path: "/algoviz/strings" },
  { slug: "stack", title: "Stack", principle: "LIFO - Last In, First Out", path: "/algoviz/stack" },
  { slug: "queue", title: "Queue", principle: "FIFO - First In, First Out", path: "/algoviz/queue" },
  { slug: "linked-list", title: "Linked List", principle: "The Chain of Nodes", path: "/algoviz/linked-list" },
  { slug: "doubly-linked-list", title: "Doubly Linked List", principle: "The Two-Way Chain", path: "/algoviz/doubly-linked-list" },
  { slug: "trees", title: "Trees", principle: "The Hierarchical Structure", path: "/algoviz/trees" }
];
var list_modules_default = defineTool({
  name: "list_modules",
  title: "List learning modules",
  description: "List every CodeBuddy data-structure learning module with its slug, title, guiding principle, and in-app path.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(MODULES, null, 2) }],
    structuredContent: { modules: MODULES }
  })
});

// src/lib/mcp/tools/get-module.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var DETAILS = {
  arrays: {
    title: "Arrays",
    principle: "The Contiguous Block",
    summary: "Fixed-order collection stored contiguously; O(1) index access, O(n) insert/delete in the middle.",
    path: "/algoviz/arrays"
  },
  strings: {
    title: "Strings",
    principle: "The Immutable Chain",
    summary: "Immutable ordered sequence of characters. Common ops: reverse, palindrome check, slicing.",
    path: "/algoviz/strings"
  },
  stack: {
    title: "Stack",
    principle: "LIFO - Last In, First Out",
    summary: "Push/pop from the top. Powers undo, browser back button, function call stacks.",
    path: "/algoviz/stack"
  },
  queue: {
    title: "Queue",
    principle: "FIFO - First In, First Out",
    summary: "Enqueue at the back, dequeue from the front. Powers print queues, task scheduling.",
    path: "/algoviz/queue"
  },
  "linked-list": {
    title: "Linked List",
    principle: "The Chain of Nodes",
    summary: "Nodes linked by pointers. O(1) insert/delete at head, O(n) traversal.",
    path: "/algoviz/linked-list"
  },
  "doubly-linked-list": {
    title: "Doubly Linked List",
    principle: "The Two-Way Chain",
    summary: "Each node points to both neighbors, enabling bidirectional traversal.",
    path: "/algoviz/doubly-linked-list"
  },
  trees: {
    title: "Trees",
    principle: "The Hierarchical Structure",
    summary: "Hierarchical nodes with parent-child links. BSTs give O(log n) search/insert on average.",
    path: "/algoviz/trees"
  }
};
var get_module_default = defineTool2({
  name: "get_module",
  title: "Get module details",
  description: "Fetch the title, guiding principle, plain-language summary, and in-app path for a CodeBuddy module.",
  inputSchema: {
    slug: z.enum([
      "arrays",
      "strings",
      "stack",
      "queue",
      "linked-list",
      "doubly-linked-list",
      "trees"
    ]).describe("Module slug, e.g. 'arrays' or 'linked-list'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const module = DETAILS[slug];
    if (!module) {
      return { content: [{ type: "text", text: `Unknown module: ${slug}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(module, null, 2) }],
      structuredContent: module
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "codebuddy-mcp",
  title: "CodeBuddy MCP",
  version: "0.1.0",
  instructions: "Tools for CodeBuddy, an interactive data-structures learning app. Use `list_modules` to see every available module and `get_module` to fetch details about a specific one.",
  tools: [list_modules_default, get_module_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
